cluster.name: "docker-cluster"
network.host: 0.0.0.0


## X-Pack 세팅
## 자세한 내용은 https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true