FROM elasticsearch:7.0.0
RUN bin/elasticsearch-plugin install --batch analysis-nori
RUN bin/elasticsearch-plugin install --batch https://github.com/javacafe-project/elasticsearch-plugin/releases/download/v7.0.0/javacafe-analyzer-7.0.0.zip
